config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'search#search_ru'
  get 'search', to: 'search#search'
  get 'search_ru', to: 'search#search_ru'
  get 'show_ru', to: 'search#show_ru'
  
  get 'show', to: 'search#show'
  
  resources :abrecs do
      collection { post :import }
  end    

end

app/models/abrec.rb
class Abrec < ActiveRecord::Base
  
  paginates_per 20
  
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  
end
Abrec.import
  

app/controllers/abrecs_controller.rb
class AbrecsController < ApplicationController
  
  def import
    Abrec.import(params[:file])
    redirect_to root_url, notice: "Humans imported."
  end

  def show
      if params[:id].nil?
        h = []
      else
        h = Abrec.search(params[:id])
      end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
   USERNAME, PASSWORD = "usr", "111"
  ip_addr = ""
if ip_addr != "127.0.0.1"
  before_filter :authenticate
end

  
  def search
    @prev_org = params[:fil]
    @abs = params[:q]
    if @prev_org.nil?
      @prev_org = params[:org]
    end
    if @abs.nil?
      @abs = params[:fraz]
    end
    qu1 = params[:fil]
      if qu1.nil?
        
      else
        #@orgs = Org.search(qu1) 
      end
    @mp = params[:fil]
    qu =  @prev_org.to_s()+ " "+ @abs.to_s() + "*"
      if qu.nil?
        @abrecs = []
      else
        @abrecs = Abrec.search(qu).page(params[:page]).per(15)
      end
  end
  
  def search_ru
    @prev_org = params[:fil]
    @abs = params[:q]
    if @prev_org.nil?
      @prev_org = params[:org]
    end
    if @abs.nil?
      @abs = params[:fraz]
    end
    qu1 = params[:fil]
      if qu1.nil?
        qu1 = params[:org]
      else
        #@orgs = Org.search(qu1) 
      end
    @mp = params[:fil]
    qu =  @prev_org.to_s()+ " "+ @abs.to_s() + "*"
      if qu.nil?
        @abrecs = []
      else
        @abrecs = Abrec.search(qu).page(params[:page]).per(15)
      end
  end
  
 def show
      if params[:id].nil?
        @hum = []
      else
        @hum = Abrec.find(params[:id])
      end
  end
  
  def show_ru
      if params[:id].nil?
        @hum = []
      else
        @hum = Abrec.find(params[:id])
      end
  end
  
private
  def authenticate
    @ip = request.ip
    authenticate_or_request_with_http_basic do |username, password|
      username == USERNAME &&
      password == PASSWORD
    end
  end 
   
end

app/helpers/abrecs_helper.rb
module AbrecsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phonebook</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/search.html.erb
<div class="small-12 large-2 columns">
  	<%= link_to "RU", controller: "search", action: "search_ru", org:@prev_org,fraz:@abs%>
  </div>

<div class="row">
  
  <center><h1>Cartea de telefoane IS Moldelectrica</h1></center>
  
</div>

<div class="row">
	<%= form_for search_ru_path, method: :get do |f| %>
        <br><br>
        <% if @prev_org.nil?%>
        <% @prev_org = "" %>
        <% end %>
        <%= select_tag :fil, options_for_select(["","IS Moldelectrica","RETI NORD-VEST", 
        	"RETI NORD", "RETI CENTRU" , "RETI SUD" ],@prev_org)%>
    	<%= text_field_tag :q, @abs %>
    	<center><%= submit_tag "Search", name: nil %></center>
    
   <br>
  
<% end %> 
</div>


<center>
<table>
  <thead>
    <tr>
      <th width="200">Intreprindere</th>
      <th>FIO</th>
      <th width="150">Telephone</th>
      <th width="150">E-mail</th>
      <th width="150">Action</th>
    </tr>
  </thead>
  <%= paginate @abrecs %>
  <tbody>
  <% i=1 %>  
  <% @abrecs.each do |human| %>
  <% if human.runame > "" %>         	    	
    <tr>
      <td><%= human.org %></td>
      <td><%=  human.rosurname %>
      	<%=  human.roname %>
      	<%=  human.rofname %>
      	</td>
      <td><center><%=  human.rtel %></center></td>
      <td><%=  human.email %></td>
      <td><li>
        <%= link_to "show", controller: "search", action: "show", id: human._id%>
        </li></td>
    </tr>
    
    <% end %>   	   
  <% end %>
  </tbody>
</table>
</center>

app/views/search/search_ru.html.erb
<div class="small-12 large-2 columns">
  	<%= link_to "MD", controller: "search", action: "search", org:@prev_org,fraz:@abs%>
  </div>
<div class="row">
	
  <center><h1>Телефонная книга IS Moldelectrica</h1></center>
</div>

<div class="row">
	<%= form_for search_ru_path, method: :get do |f| %>
	
        <br><br>
        <% if @prev_org.nil?%>
        <% @prev_org = "" %>
        <% end %>
        <%= select_tag :fil, options_for_select(["","IS Moldelectrica","RETI NORD-VEST", 
        	"RETI NORD", "RETI CENTRU" , "RETI SUD" ],@prev_org)%>
    	<%= text_field_tag :q, @abs%>
    	<center><%= submit_tag "Искать", name: nil %></center>
    
   <br>
  
<% end %> 
</div>
 

<center>
<table>
  <thead>
    <tr>
      <th width="200">Предприятие</th>
      <th>ФИО</th>
      <th width="150">Рабочий телефон</th>
      <th width="150">E-mail</th>
      <th width="150">Действие</th>
    </tr>
  </thead>
  <tbody>
  
  <% i=1 %>  
  <% @abrecs.each do |human| %>
  <% if human.runame > "" %>         	    	
    <tr>
      <td><%= human.org %></td>
      <td><%=  human.rusurname %>
      	<%=  human.runame %>
      	<%=  human.rufname %>
      	</td>
      <td><center><%=  human.rtel %></center></td>
      <td><%=  human.email %></td>
      <td><li>
        <%= link_to "Показать", controller: "search", action: "show_ru", id: human._id%>
        </li></td>
    </tr>
    
    <% end %>   	   
  <% end %>
  <%= paginate @abrecs %>
  </tbody>
</table>
</center>

app/views/search/show.html.erb
<center>
<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
    <div class="row">
  <div class="small-2 large-4 columns">
  	<%= link_to "RU", controller: "search", action: "show_ru", id: @hum.id%>
  </div>
  <div class="small-4 large-4 columns"></div>
  <div class="small-6 large-4 columns">
  	<%= link_to "Inapoi", controller: "search", action: "search", id: @hum.id%>
  </div>
</div>
  </nav>
</div>
<div class="row">
  <div class="small-2 large-4 columns">
  	..
  </div>
  <div class="small-4 large-4 columns">
  	<div class="panel"> 
	
	<p>Companie : <%= @hum.org %></p><br>
	<p>Positie : <%= @hum.position %></p><br>
	<p>Telephone : <%= @hum.rtel %></p><br>
	<p>Name : <%= @hum.roname %></p><br>
	<p>Surname : <%= @hum.rosurname %></p><br>
	<p>Telefonul mobil : <%= @hum.mtel %></p><br>
	<p>Email : <%= @hum.email %></p><br>
	
	</div>
  </div>
  <div class="small-6 large-4 columns">
  	..
  </div>
</div>
	
</center>


<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
    ...
  </nav>
</div>

app/views/search/show_ru.html.erb
<center>

<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
    <div class="row">
  <div class="small-2 large-4 columns">
  	<%= link_to "MD", controller: "search", action: "show", id: @hum.id%>
  </div>
  <div class="small-4 large-4 columns"></div>
  <div class="small-6 large-4 columns">
  	<%= link_to "Назад", controller: "search", action: "search", id: @hum.id%>
  </div>
</div>
  </nav>
</div>

<div class="row">
  <div class="small-2 large-4 columns">
  	..
  </div>
  <div class="small-4 large-4 columns">
  	<div class="panel"> 

<div class="row">
	<p>Предприятие : <%= @hum.org %></p><br>
	<p>Рабочий телефон : <%= @hum.rtel %></p><br>
	<p>Имя : <%= @hum.runame %></p><br>
	<p>Фамилия : <%= @hum.rusurname %></p><br>
	<p>Отчество : <%= @hum.rufname %></p><br>
	<p>Мобильный телефон : <%= @hum.mtel %></p><br>
	<p>Электронная почта : <%= @hum.email %></p><br>
	
</div>
	</div>
  </div>
  <div class="small-6 large-4 columns">
  	..
  </div>
</div>
</center>
<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
    ...
  </nav>
</div>